package errors

var enUSText = map[int]string{
	SUCCESS:                   "OK",
	FAILURE:                   "FAIL",
	NotFound:                  "resources not found",
	ServerErr:                 "Internal server error",
	TooManyRequests:           "Too many requests",
	InvalidParameter:          "Parameter error",
	UserDoesNotExist:          "user does not exist",
	UserDisable:               "User is disabled",
	ServiceDependencyNotReady: "service database is not configured, please contact the administrator",
	AuthorizationErr:          "You have no permission",
	NotLogin:                  "Please login first",
	CaptchaErr:                "Captcha error",
	FileIdentifierInvalid:     "invalid file identifier",
	FilePrivateAuthNeeded:     "login required for private file access",
	FileAccessDenied:          "no permission to access this file",
	FileUploadPartialFail:     "partial image upload failure",

	// Business error messages 20000-29999
	UserPasswordWrong:       "Incorrect password",
	UserExists:              "User already exists",
	PhoneNumberExists:       "Phone number already exists",
	EmailExists:             "Email already exists",
	UsernameRequired:        "Username is required",
	NicknameRequired:        "Nickname is required",
	PasswordProcessFailed:   "Password processing failed",
	SuperAdminCannotModify:  "Cannot modify default super admin password",
	SuperAdminCannotDisable: "Cannot disable default super admin",
	SuperAdminCannotDelete:  "Cannot delete default super admin",
	SamePassword:            "New password cannot be the same as current password",
	RoleNotFound:            "Role not found",
	RoleExists:              "Role already exists",
	RoleHasChildren:         "Cannot delete role with child roles",
	RoleCannotDelete:        "Failed to delete role",
	ParentRoleNotExists:     "Parent role not exists",
	ParentRoleInvalid:       "Parent role cannot be itself or its child role",
	MaxRoleDepth:            "Can only create up to 2 levels of roles",
	MaxChildRoles:           "Each top-level role can have up to %d child roles",
	MenuNotFound:            "Menu not found",
	MenuExists:              "Menu already exists",
	MenuHasChildren:         "Cannot delete menu with child menus",
	MenuCannotDelete:        "Failed to delete menu",
	DepartmentNotFound:      "Department not found",
	DepartmentExists:        "Department already exists",
	DepartmentHasChildren:   "Cannot delete department with child departments",
	DepartmentCannotDelete:  "Failed to delete department",
	ParentDeptNotExists:     "Parent department not exists",
	ParentDeptInvalid:       "Parent department cannot be itself or its child department",
	MaxDeptDepth:            "Department level exceeds limit",
	CasbinInitFailed:        "Permission initialization failed",
	TokenGenerateFailed:     "Failed to generate token",
	LoginFailed:             "Login failed, please try again later",
	CreateUserFailed:        "Failed to create user, please try again",
	UpdateUserFailed:        "Failed to update user, please try again",
	DeleteUserFailed:        "Failed to delete user, please try again",
	QueryUserDeptFailed:     "Failed to query user department association",
	SuperAdminMustKeepRole:  "Default super admin must keep super admin role",
}
