package errors

var zhCNText = map[int]string{
	SUCCESS:                   "OK",
	FAILURE:                   "FAIL",
	NotFound:                  "资源不存在",
	InvalidParameter:          "参数错误",
	ServerErr:                 "服务器内部错误",
	TooManyRequests:           "请求过多",
	UserDoesNotExist:          "用户不存在",
	UserDisable:               "用户已被禁用",
	ServiceDependencyNotReady: "服务暂未配置数据库，请联系管理员",
	AuthorizationErr:          "暂无权限",
	NotLogin:                  "请先登录",
	CaptchaErr:                "验证码错误",

	// 文件相关错误消息 11000-11999
	FileIdentifierInvalid: "文件标识错误",
	FilePrivateAuthNeeded: "访问私有文件需要登录认证",
	FileAccessDenied:      "无权访问该文件",
	FileUploadPartialFail: "部分图片上传失败",

	// 业务错误消息 20000-29999
	UserPasswordWrong:       "用户密码错误",
	UserExists:              "用户已存在",
	PhoneNumberExists:       "手机号已存在",
	EmailExists:             "邮箱已存在",
	UsernameRequired:        "用户名必填",
	NicknameRequired:        "昵称必填",
	PasswordProcessFailed:   "密码处理失败",
	SuperAdminCannotModify:  "系统默认超级管理员不允许修改密码",
	SuperAdminCannotDisable: "系统默认超级管理员不允许被禁用",
	SuperAdminCannotDelete:  "系统默认超级管理员不允许删除",
	SamePassword:            "新密码不能与当前密码相同",
	RoleNotFound:            "角色不存在",
	RoleExists:              "角色已存在",
	RoleHasChildren:         "该角色有子角色，无法删除",
	RoleCannotDelete:        "删除角色失败",
	ParentRoleNotExists:     "上级角色不存在",
	ParentRoleInvalid:       "上级角色不能是当前角色自身或其子角色",
	MaxRoleDepth:            "最多只能创建2层角色",
	MaxChildRoles:           "每个顶级角色下最多只能创建5个子角色",
	MenuNotFound:            "菜单不存在",
	MenuExists:              "菜单已存在",
	MenuHasChildren:         "该菜单有子菜单，无法删除",
	MenuCannotDelete:        "删除菜单失败",
	DepartmentNotFound:      "部门不存在",
	DepartmentExists:        "部门已存在",
	DepartmentHasChildren:   "该部门有子部门，无法删除",
	DepartmentCannotDelete:  "删除部门失败",
	ParentDeptNotExists:     "上级部门不存在",
	ParentDeptInvalid:       "上级部门不能是当前部门自身或其子部门",
	MaxDeptDepth:            "部门层级超出限制",
	CasbinInitFailed:        "权限验证初始化失败",
	TokenGenerateFailed:     "生成Token失败",
	LoginFailed:             "登录失败，请稍后重试",
	CreateUserFailed:        "创建用户失败，请重试",
	UpdateUserFailed:        "更新用户失败，请重试",
	DeleteUserFailed:        "删除用户失败，请重试",
	QueryUserDeptFailed:     "查询用户部门关联失败",
	SuperAdminMustKeepRole:  "系统默认超级管理员必须保留超级管理员角色",
	MaxMenuDepth:            "最多只能创建 4 层菜单",
	ParentMenuNotExists:     "上级菜单不存在",
	ParentMenuTypeInvalid:   "上级菜单不能是按钮类型",
	ParentMenuInvalid:       "上级菜单不能是当前菜单自身或其子菜单",
	MenuCodeExists:          "权限标识已存在",
	MenuRouteNameExists:     "路由名称已存在",
	MenuPathExists:          "路由已存在",
}

var zhCNTextKey = map[string]string{
	MsgKeyAuthSessionExpired:        "登录已失效，请重新登录",
	MsgKeyAuthPermissionInitFailed:  "权限验证初始化失败",
	MsgKeyAuthPermissionCheckFailed: "权限验证失败",
	MsgKeyAuthAPIOperationDenied:    "暂无接口操作权限",
}
